config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :photos

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at:"/letter_opener"
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
    validates :name, :content, :photo, presence: true #バリデーションの設定
    mount_uploader :photo,PhotoUploader  #carrierwaveの設定
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  #ログインしていなければ投稿機能を使用できないようにする(Deviseのauthenticate_user!メソッドを使用)
  before_action :authenticate_user!

  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  # before_action :check_user

  # GET /photos
  def index
    @photos = Photo.all
    
  end


  # GET /photos/new
  def new

    if params[:back]
      @photo =  Photo.new(photo_params)
    else
      @photo = Photo.new
    end

  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    @photo.user_id = current_user.id #user_idカラムにユーザーidを格納

      #photoテーブルの書き込み時の処理
      if @photo.save
        redirect_to photos_url, notice: '写真が投稿されました'
        # render :show, status: :created, location: @photo
      else
        render :new
      end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photos_url, notice: '写真が更新されました！.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: '写真の削除が完了しました' }
    end
  end

  private

    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:name, :content, :user_id, :photo)
    end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

    <%= form_for(@photo) do |f| %>
      <%= f.error_messages! %>

      <div class="field">
        <%= f.text_field :name, placeholder:"タイトル", class:'form-control' %>
      </div>
      <br/>

      <div class="field">
        <%= f.text_field :content , placeholder:"コメント", class:'form-control' %>
      </div>

      <div class="field">
          <h3>投稿画像</h3>
        <!-- <＃%= profile_img(@photo) if profile_img(@photo) %> -->
          <%= image_tag(@photo.photo, :size => "200x200")%>
          <%= f.file_field :photo %>
          <%= f.hidden_field :photo_cache %>
      </div>

      <div class="actions">
        <%= f.submit "登録", method:'post', class:'btn btn-block btn-primary'%>
      </div>
    <% end %>

  </div>
</div>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>投稿一覧</h1>

<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

  <%= button_to '新規投稿', new_photo_path, method:'get', class:"btn btn-default" %>

  <table>
    <thead>
      <tr>
        <th>投稿者</th>
        <th>名前</th>
        <th>コメント</th>
        <th>写真</th>
        <th colspan="10"></th>
      </tr>
    </thead>

    <tbody>
      <% @photos.each do |photo| %>
        <tr>
          <!-- <＃% binding.pry %> -->
          <td><%= image_tag(User.find(photo.id).avatar)%></td>
          <td><%= photo.name %></td>
          <td><%= photo.content %></td>
          <td><%= image_tag(photo.photo) %></td>
          <td><%= button_to '編集', edit_photo_path(photo), method:'get', class:"btn btn-block btn-info" %></td>
          <td><%= button_to '削除', photo_path(photo), method:'delete',data: { confirm: '本当に削除しますか？'}, class:"btn btn-block btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


  </div>
</div>

app/views/photos/new.html.erb
<h1>新しい写真を投稿</h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @photo.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @photo.content %>
</p>

<!-- <p>
  <strong>User:</strong>
  <%= @photo.user_id %>
</p> -->

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>